# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0940b354ef073ca2ffbbb4b9f96e37fdf2d42278853a83d590e8567685f7f656229c7b1fdf597d9b5de323acd8b29d09a7fb71c9e700c13c17a027d9e608d2ad

test:
  secret_key_base: 1b1ad2c70d41969650bcb6ba1abfd798e838c5f08dc1c74a0589c45bac332e97b47fc8d7098d47e21fc5cd1ebb1bdf38557570f7d9a179779b012bf92baadaae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
